import Head from 'next/head';
import Slidebar from '../components/Slidebar';

export default function Home() {
  return (
    <div >
      <Head>
        <title>whatsapp 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Slidebar/>
    </div>
  )
}
